name: gradle-ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build artifacts
      run: ./gradlew build
    - name: Delete dev artifacts
      run: |
        find bastion/build/libs/ -name '*-dev.jar' -delete
        find classic/build/libs/ -name '*-dev.jar' -delete
        find monument/build/libs/ -name '*-dev.jar' -delete
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          bastion/build/libs/*
          classic/build/libs/*
          monument/build/libs/*
